### ISSUE TITLE
每次请求的session ID都在变化

### ISSUE THREAD

**Issue by skyhuihui** [go-session/session#1]
每次请求的sessionid 值都在变化， 信息存进session ， 获取不到

**Comment by skyhuihui** [comment]
postman ，  请求可以， session id 不会变， 客户端请求 就不行

**Comment by LyricTian** [comment]
能贴一下你的示例代码吗，顺便看一下浏览器的cookie是否启用了呢

**Comment by skyhuihui** [comment]
加个微信， 不知道怎么回事，代码传不上来

**Comment by skyhuihui** [comment]
18238021197
