### ISSUE TITLE
Help !!

### ISSUE THREAD

**Issue by p000ic** [go-session/session#15]
Does the latest `v3` session work with `mongodb` ?

**Comment by LyricTian** [comment]
The latest mongo version has been support session v3, please try it again.

https://github.com/go-session/mongo

**Comment by p000ic** [comment]
Hi Lyric,  As the mongo session uses `mgo` package [which comes under a different license], I had to implement these logic with different library. Really appreciate the reference. Thank you.

In-case if you are interested, take a peek [go-mongo-session](https://github.com/p000ic/go-mongo-session). I'm up for review comment.

Again, thanks for the response.
