### ISSUE TITLE
go mod import error

### ISSUE THREAD

**Issue by edieruby** [go-session/session#4]
go mod download get the error 
require github.com/go-session/session: version "v3.1.3" invalid: module contains a go.mod file, so major version must be compatible: should be v0 or v1, not v3.

**Comment by LyricTian** [comment]
Thanks!Has been update releated dependency,try again!

**Comment by edieruby** [comment]
sorry still not work.
need to create a v3 fold or create a v3 branch?
https://github.com/golang/go/issues/35732

**Comment by kevincobain2000** [comment]
Still the same

**Comment by kevincobain2000** [comment]
Can you please have a look into it? I think you need to update the go.mod file for any versions that are >= 2
Thanks

**Comment by kevincobain2000** [comment]
Hi @LyricTian - Would you be able to push the new ``/v3`` in the go.mod?
